### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kjhughes** [IamIntrovert/Introvert#3]
[Website](https://iamintrovert.co/) says "Use the code in any way."  [Add a license file](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to the repository to make your intention clear.

Thank you for creating and making your source available.

**Comment by digitaldesigndj** [comment]
Use any way you like is most similar to MIT license. You’ll reserve just one right, others must attribute the work. (Can’t just change author name).

**Comment by IamIntrovert** [comment]
Just added MIT, thanks!
